### ISSUE TITLE
参数求助

### ISSUE THREAD

**Issue by burberrys** [ffwen123/plugin_midjourney_v2#1]
![image](https://github.com/ffwen123/plugin_midjourney_v2/assets/49263337/ecb24e43-771c-49bd-aa85-0cc5c0993890)
想问下大佬这几个参数ID在哪里获取

**Comment by ffwen123** [comment]
> ![图像](https://user-images.githubusercontent.com/49263337/242474572-ecb24e43-771c-49bd-aa85-0cc5c0993890.png) 想问下大佬这几个参数ID在哪获得
api_url：来自https://github.com/novicezk/midjourney-proxy自建；
oss是阿里的
